name: create-msys2

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]
        cppstd: [None, 17]
        exception_platform: [seh-x86_64]
        profile: [msys2_mingw]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"
      - run: python -m pip install --upgrade pip conan gitpython
        shell: cmd
      - run: |
          cd conan
          conan profile new default --detect --force
          build.bat ${{ matrix.exception_platform }} -s build_type=${{ matrix.build_type }} -s compiler.cppstd=${{ matrix.cppstd }}
        shell: cmd
        env:
          CONAN_REQUEST_TIMEOUT: 120
